name: Run Node.js Script Daily

on:
  schedule:
    - cron: '0 1 * * *'  # 台灣時間 06:00（UTC+8）
  workflow_dispatch: # 允許手動執行

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 設定 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run the script
        run: npm run start
